# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Facebook SDK
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'

  # Firebase
	pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'

  #SDImage
    pod 'SDWebImage'
    pod 'SDWebImage/WebP'

end
